apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
        - name: integration-service
          image: weeranh/integration-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: integration-service-db-secret
                  key: DATABASE_URL
