apiVersion: batch/v1
kind: CronJob
metadata:
  name: integration-test-integration-service
spec:
  schedule: "0 * * * *" # Run every hour (at the start of the hour)
  # Prevent concurrent runs if the previous one hasn't finished yet
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600 # Keep pod for 10 min after completion
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: integration-test-integration-service
              image: us-central1-docker.pkg.dev/moon-insurance/moon-insurance/integration-service:latest
              command: ["pytest", "tests/integration-test.py"]
              resources:
                requests:
                  cpu: "250m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "256Mi"
              env:
                - name: BASE_URL
                  value: "http://mooninsurance.com"
